import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { getCurrentUser } from "./lib/auth";
import { redirect } from "next/navigation";
import clsx from "clsx";
import { montserrat } from "@component/fonts/font";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = getCurrentUser();

  // if (!user) {
  //   redirect('/auth'); // Not authenticated, send to login
  // }

  return (
    <html lang="en">
      <body className={clsx(`antialiased` , montserrat.className)}>
        <Navbar />
        {/* {user.name} */}
        {children}
      </body>
    </html>
  );
}
